# 로컬 전용 docker-compose

networks:
  lol-local-network:
    name: lol-local-network
    driver: bridge

services:
  # MySQL
  mysql:
    container_name: lol.local.mysql
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - TZ=Asia/Seoul
    volumes:
      - ./data/mysql-data:/var/lib/mysql
      - ./data/mysql-files:/var/lib/mysql-files
      - ./data/mysql-log:/var/tmp
    command:
      - --character-set-server=utf8mb4
      - --log_timestamps=SYSTEM # 로그는 기본값이 UTC 여서 명시적으로 변경해야 한다.
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake # 클라이언트 character set 값을 보낼 때 서버에서 이를 무시하는 명령어, docker linux에서 locale 설정하지 않아 default 값인 latin1로 설정
      - --lower_case_table_names=1
    networks:
      - lol-local-network