# -----------------------------
#       COMMON SETTINGS
# -----------------------------
spring:
  jpa:
    open-in-view: false
  task:
    scheduling:
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

decorator:
  datasource:
    p6spy:
      enable-logging: true

# riot api key
riot:
  api:
    key: ${RIOT_API_KEY}

discord:
  game-start:
    url: ${DISCORD_GAME_START_WEBHOOK_URL}
  level-up:
    url: ${DISCORD_LEVEL_UP_WEBHOOK_URL}
  daily-statistics:
    url: ${DISCORD_DAILY_STATISTICS_WEBHOOK_URL}
  weekly-statistics:
    url: ${DISCORD_WEEKLY_STATISTICS_WEBHOOK_URL}
  monthly-statistics:
    url: ${DISCORD_MONTHLY_STATISTICS_WEBHOOK_URL}
---
# -----------------------------
#       LOCAL SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: local
  application:
    name: lol.local.server.api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DOCKER_MYSQL_URL}
    username: ${DOCKER_MYSQL_USERNAME}
    password: ${DOCKER_MYSQL_PASSWORD}
---
# -----------------------------
#       PROD SETTINGS
# -----------------------------
spring:
  config:
    activate:
      on-profile: prod
  application:
    name: lol.prod.server.api
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${PROD_DOCKER_MYSQL_URL}
    username: ${PROD_DOCKER_MYSQL_USERNAME}
    password: ${PROD_DOCKER_MYSQL_PASSWORD}